version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: whiteboarddb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: 
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app

  frontend:
    image: node:20-alpine
    working_dir: /app/frontend
    volumes:
      - ./whiteboard-frontend:/app/frontend
      - /app/frontend/node_modules
    environment:
      VITE_BACKEND_URL: "http://localhost:8000"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "3000:3000"
    depends_on:
      - web

volumes:
  db_data:
